version: '3.7'

services:
  db:
    image: postgres:alpine
    container_name: dsandapostrgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_USER: dsanda
      POSTGRES_DB: postgresdb
    ports:
      - 5432:5432
    volumes:
      - dsanda_postgres:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  dsanda_postgres: