version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: "dsandal_db"
    restart: always
    environment:
      - POSTGRES_USER=dsanda
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=postgresdb
    ports:
      - "5432:5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    container_name: "dsandal_api"
    environment:
      DB_USERNAME: dsanda
      DB_PASSWORD: postgrespass
      DB_DB: postgresdb
      DB_HOST: db
      DB_PORT: "5432"
    ports: 
      - "9010:9010"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_postgres:

networks:
  backend:
    driver: bridge
