version: '3.7'

services:
  db:
    image: postgres:alpine
    container_name: dsandapostrgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - dsanda_postgres:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  dsanda_postgres: